backend:
  name: git-gateway
  branch: cimusa # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "FAQ"
    name: "faq"
    files:
      - label: "FAQ (en)"
        name: "faq (en)"
        file: "data/en/faq.yml"
        fields:
          - label: FAQ (en)
            name: faqItem
            widget: list
            fields:
              - {label: ID, name: ID, widget: select, options: ["collapseOne", "collapseTwo", "collapseThree", "collapseFour", "collapseFive", "collapseSix", "collapseSeven", "collapseHeight"]}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
      - label: "FAQ (fr)"
        name: "faq (fr)"
        file: "data/fr/faq.yml"
        fields:
          - label: FAQ (fr)
            name: faqItem
            widget: list
            fields:
              - {label: ID, name: ID, widget: select, options: ["collapseOne", "collapseTwo", "collapseThree", "collapseFour", "collapseFive", "collapseSix", "collapseSeven", "collapseHeight"]}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}